# fly.toml app configuration file generated for api-spring-cloud-3523 on 2025-06-07T21:12:12+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-spring-cloud-3523'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
