# fly.toml app configuration file generated for api-misty-resonance-369 on 2025-03-31T14:23:19+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-misty-resonance-369'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'
